### ISSUE TITLE
Features and TO-DO List

### ISSUE THREAD

**Issue by alexandremendoncaalvaro** [alexandremendoncaalvaro/face-access#1]
- [x] Basic command line interface
- [x] Face recogniton from Webcam
- [x] Just use the photo once for register, after that discard. Save only a id on the local file database (LGPDP Brasil Safe).
- [x] OneTimePassword with Google Authenticator
- [x] Text to Speech for welcome audio message
- [x] Arduino commands to open the door
- [x] Qr-Code to easy registration and temporary access
- [ ] Audio code (CHIRP) to easy registration and temporary access
- [x] Multithread support
- [x] GPU support
- [ ] Improve performance with Region Of Interest method (https://github.com/hrastnik/face_detect_n_track)

**Comment by alexandremendoncaalvaro** [comment]
Alread in the readme
